name: CI | Run cri-containerd tests
on:
  workflow_call:
    inputs:
      tarball-suffix:
        required: false
        type: string
      commit-hash:
        required: false
        type: string
      target-branch:
        required: false
        type: string
        default: ""
      runner:
        description: The runner to execute the workflow on.
        required: true
        type: string
      arch:
        description: The arch of the tarball.
        required: true
        type: string
      containerd_version:
        description: The version of containerd for testing.
        required: true
        type: string
      vmm:
        description: The kata hypervisor for testing.
        required: true
        type: string

jobs:
  run-cri-containerd:
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.runner }}
    env:
      CONTAINERD_VERSION: ${{ inputs.containerd_version }}
      GOPATH: ${{ github.workspace }}
      KATA_HYPERVISOR: ${{ inputs.vmm }}
    steps:
      - name: Clean up workspace
        run: |
          if [ -z "${GITHUB_WORKSPACE}" ]; then
            echo "ERROR: GITHUB_WORKSPACE is not set"
            exit 1
          fi

          workspace_dir=$(sudo realpath "$GITHUB_WORKSPACE")
          runner_base_dir=/home/github-runner/actions-runner/_work

          if [[ $workspace_dir == $runner_base_dir* ]]; then
            sudo find $GITHUB_WORKSPACE -mindepth 1 -delete
          else
            echo "ERROR: GITHUB_WORKSPACE ($GITHUB_WORKSPACE) must be within $runner_base_dir"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Rebase atop of the latest target branch
        run: |
          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
        env:
          TARGET_BRANCH: ${{ inputs.target-branch }}

      - name: Install dependencies
        timeout-minutes: 15
        run: bash tests/integration/cri-containerd/gha-run.sh install-dependencies

      - name: get-kata-tarball for ${{ inputs.arch }}
        uses: actions/download-artifact@v4
        with:
          name: kata-static-tarball-${{ inputs.arch }}${{ inputs.tarball-suffix }}
          path: kata-artifacts

      - name: Install kata
        run: bash tests/integration/cri-containerd/gha-run.sh install-kata kata-artifacts

      - name: Run cri-containerd tests for ${{ inputs.arch }}
        run: bash tests/integration/cri-containerd/gha-run.sh run
